
import type { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Casa Parque Granja Esperança',
    type: 'Casa',
    description: 'Bataglin imóveis vende\n\nCasa 2 dormitórios\n\nTerreno 120m² 6x20\n\nCasa 67 m²\n\nCom área gourmet nos fundos , com churrasqueira, fogão, pia , mesa e banheiro.\n\nAs informações estão sujeitas a alterações. Consulte o corretor responsável.',
    price: 228000,
    location: 'Rua Maria Ana da Costa - Parque Granja Esperança - Cachoeirinha/RS - 94960-800',
    bedrooms: 2,
    bathrooms: 2, // 1 na casa + 1 na área gourmet
    area: 67,
    images: [
      '/casaparquegranjaesperança/capaprincipal.jpg',
      '/casaparquegranjaesperança/foto1.jpg',
      '/casaparquegranjaesperança/foto2.jpg',
      '/casaparquegranjaesperança/foto3.jpg',
      '/casaparquegranjaesperança/foto4.jpg',
      '/casaparquegranjaesperança/foto5.jpg',
      '/casaparquegranjaesperança/foto6.jpg',
    ],
    features: ['Área Gourmet com Churrasqueira', '2 Dormitórios', 'Vaga de Garagem'],
    featured: true,
  },
  {
    id: '2',
    title: 'Apartamento em Porto Gravataí',
    type: 'Apartamento',
    description: 'Ótima Localização e praticidade\n\nBuscando uma moradia com ótima localização, aqui está a oportunidade pra você.\n\nEste ótimo apto. com 2 dormitórios, mobiliado e condominio com toda a infraestrutura, um belíssimo salão de festas, piscinas adulto e infantil, playground, brinquedoteca e quiosques com churrasqueiras.\n\nLocalizado em uma região privilegiada, junto a av Dorival C. L. de Oliveira na pda 72, com uma rica infraestrutura comercial onde você vai ter farmácias, mercado, bazar, lotérica, ponto de ônibus há poucos metros de distância.\n\nPraticidade, comodidade e segurança são as palavras chaves que definem esse imóvel, sem falar no ótimo custo benefício.\n\nESPERAMOS VOCÊ PARA CONHECER ESSA OPORTUNIDADE!!!\n\nAs informações estão sujeitas a alterações. Consulte o corretor responsável.',
    price: 168000,
    location: 'Porto Gravataí - São Jerônimo - Gravataí/RS',
    bedrooms: 2,
    bathrooms: 1,
    area: 0, 
    images: [
      '/apartamento/capa.jpg',
      '/apartamento/img1.jpg',
      '/apartamento/img2.jpg',
      '/apartamento/img3.jpg',
      '/apartamento/img4.jpg',
      '/apartamento/img5.jpg',
      '/apartamento/img6.jpg'
    ],
    features: ['1 Vaga de Garagem', 'Mobiliado', 'Piscina no Condomínio', 'Salão de Festas', 'Playground', 'Quiosques com Churrasqueira'],
    featured: true,
  },
  {
    id: '3',
    title: 'Apartamento 3 Dormitórios à Venda',
    type: 'Apartamento',
    description: 'LANÇAMENTO EM CACHOEIRINHA!\n\nImóvel diferenciado com 3 dormitórios e 76 m² no bairro Vista Alegre\nO apartamento possui uma suíte, banheiro social, sala de estar, jantar, lavanderia e cozinha integrada com os ambientes sociais.\n\nA sacada com churrasqueira também é um diferencial, além de elevador e vaga de garagem coberta.\n\nA localização é excelente, há 650 metros da Avenida General Flores da Cunha, próximo ao Shopping do Vale, Carrefour, Faculdade Cesuca, Sessto Atacadão, Hospital Padre Geremias, tudo a poucos metros do imóvel.\n\nAceita financiamento bancário e FGTS\n\nEntrada facilitada pela construtora\n\nPrevisão de entrega Junho 2024\n\nEntre em contato conosco e traga a sua proposta!\n\nAs informações estão sujeitas a alterações. Consulte o corretor responsável.',
    price: 350000, 
    location: 'Rua Caruaru, 160 - Vila Vista Alegre - Cachoeirinha/RS - 94945-120',
    bedrooms: 3,
    bathrooms: 2, 
    area: 76,
    images: [
        '/apartamento3dormitoriiod/capa.jpg',
        '/apartamento3dormitoriiod/imagem1.jpg',
        '/apartamento3dormitoriiod/imagem2.jpg',
        '/apartamento3dormitoriiod/imagem3.jpg',
        '/apartamento3dormitoriiod/imagem4.jpg',
        '/apartamento3dormitoriiod/imagem5.jpg',
        '/apartamento3dormitoriiod/imagem6.jpg'
    ],
    features: ['3 Dormitórios (1 suíte)', 'Vaga de garagem coberta', 'Elevador', 'Sacada com Churrasqueira'],
    featured: true,
  },
  {
    id: '4',
    title: 'Terreno Amplo em Condomínio Fechado',
    type: 'Terreno',
    description: 'Excelente oportunidade para construir a casa dos seus sonhos. Terreno plano e espaçoso em condomínio fechado com segurança 24 horas e área de lazer completa.',
    price: 450000,
    location: 'Condomínio Vale Verde',
    bedrooms: 0,
    bathrooms: 0,
    area: 1000,
    images: ['https://placehold.co/800x600'],
    features: ['Segurança 24h', 'Clube', 'Área Verde', 'Pronto para Construir'],
    featured: false,
  },
  {
    id: '5',
    title: 'Casa em Morada do Bosque, Cachoeirinha/RS',
    type: 'Casa',
    description: 'Procurando uma casa aconchegante para chamar de lar? Esta é a opção perfeita para você! Com 3 dormitórios bem distribuídos, garagem coberta para dois veículos e mais de 70m² de área construída total , este imóvel está pronto para receber sua família com todo o conforto que vocês merecem.\n\nAlém disso, o imóvel conta com ar condicionado para os dias quentes de verão, churrasqueira e fogão campeiro em um espaço gourmet para reunir os amigos e compartilhar momentos com as pessoas que você ama.\n\nE a localização é privilegiada, próximo a tudo o que você precisa: supermercado, padaria, farmácia, banco 24hs, praça, praça, transporte público, rodovia e muito mais.\n\nLocalizada em um dos bairros mais procurados da cidade, o Morada do Bosque destaca-se por ser um local tranquilo e com ótima acessibilidade, esta casa é o lugar perfeito para você construir momentos inesquecíveis com sua família.\n\nNão perca essa oportunidade de conhecer o imóvel e muitos outros detalhes que irão te surpreender.\n\nEntre em contato conosco agora mesmo através do formulário de contato do site ou diretamente pelo whatssap.\n\nEstamos ansiosos para te ajudar a conquistar seu novo lar!',
    price: 264900,
    location: 'Morada do Bosque - Cachoeirinha/RS',
    bedrooms: 3,
    bathrooms: 1,
    area: 70,
    images: [
      '/casabosque/capa.jpg',
      '/casabosque/img2.jpg',
      '/casabosque/img3.jpg',
      '/casabosque/img4.jpg',
      '/casabosque/img5.jpg',
      '/casabosque/img6.jpg',
      '/casabosque/img7.jpg'
    ],
    features: ['Garagem coberta para 2 carros', 'Ar Condicionado', 'Espaço Gourmet com Churrasqueira', 'Fogão Campeiro'],
    featured: true,
  },
  {
    id: '6',
    title: 'Casa 1 Dormitório a venda em Cachoeirinha',
    type: 'Casa',
    description: 'Procurando um cantinho perfeito para chamar de seu em Cachoeirinha? Este imóvel pode ser exatamente o que você precisa! Com posição solar privilegiada, você poderá desfrutar do sol da manhã e da tarde todos os dias. Localizada no charmoso Residencial Vila Bela, esta casa está pertinho de tudo o que você precisa: banco 24hs, escola, farmácia, igreja, padaria, praça, rodovia, supermercado e transporte público. Ou seja, comodidade é o que não vai faltar! Se você está buscando um novo lar para chamar de seu, não perca a oportunidade de conhecer este imóvel. Com um ambiente aconchegante e agradável, ela é ideal para quem está em busca de adquirir o seu primeiro imóvel, além de praticidade, conforto e um excelente custo benefício. Não deixe essa chance passar! Entre em contato conosco através do formulário do site ou através do nosso whatsapp e agende uma visita para conhecer de perto todos os detalhes deste imóvel. Comprar casa na região que mais cresce em Cachoeirinha nunca foi tão fácil e tão vantajoso. Venha conferir! Whatsap(51)98563 2393 As informações estão sujeitas a alterações. Consulte o corretor responsável.',
    price: 150000,
    location: 'Rua Açaí, 78 - Chácara das Rosas - Cachoeirinha/RS - 94967-724',
    bedrooms: 1,
    bathrooms: 1,
    area: 0,
    images: [
      '/casa1dormitorio/capa.jpg',
      '/casa1dormitorio/img1.jpg',
      '/casa1dormitorio/img2.jpg',
      '/casa1dormitorio/img3.jpg',
      '/casa1dormitorio/img4.jpg',
    ],
    features: ['Posição Solar Privilegiada', 'Residencial Vila Bela'],
    featured: true,
  },
  {
    id: '7',
    title: 'Apartamento com 3 Suítes',
    type: 'Apartamento',
    description: 'Apartamento espaçoso com três suítes, ideal para famílias que buscam conforto e privacidade. O condomínio oferece uma infraestrutura completa de lazer.',
    price: 1500000,
    location: 'Moema',
    bedrooms: 3,
    bathrooms: 4,
    area: 160,
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600'],
    features: ['3 Suítes', 'Varanda Gourmet', 'Piscina Aquecida', 'Salão de Festas'],
    featured: false,
  },
    {
    id: '8',
    title: 'Apartamento Jardim dos Pampas I',
    type: 'Apartamento',
    description: 'Adquira seu imóvel pelo Minha Casa Minha Vida. Venha residir nessa ótima oportunidade. Apartamento com dois dormitórios, living dois ambientes, banheiro, cozinha e área de serviço. Unidade térrea com vista sem bloqueios. Ensolarado e bem ventilado. Lindo piso cerâmico, cozinha com armários e gás central. Uma vaga de garagem por rodízio (muita disponibilidade). Condomínio Jardim dos Pampas I possui portaria 24h, bicicletário, quiosques com churrasqueiras, fitness externo, playground e salão de festas. Localizado próximo a Freeway, Havan, Stok Center, Mercado Super Bom Preço, Praças, Escolas, entre outras conveniências. Preço e disponibilidade do imóvel sujeitos a alteração sem aviso prévio.',
    price: 140000,
    location: 'Avenida Souza Melo - Sarandi - Porto Alegre/RS - 91120-600',
    bedrooms: 2,
    bathrooms: 1,
    area: 41,
    images: [
        '/apartamento2/capa.jpeg',
        '/apartamento2/img1.jpeg',
        '/apartamento2/img2.jpeg',
        '/apartamento2/imagem3.jpeg',
        '/apartamento2/imagem4.jpeg',
        '/apartamento2/img5.jpeg',
        '/apartamento2/img6.jpeg'
    ],
    features: ['Portaria 24h', 'Quiosques com Churrasqueira', 'Salão de Festas', 'Playground'],
    featured: true,
  },
];
