import type { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Casa Parque Granja Esperança',
    type: 'Casa',
    description: 'Bataglin imóveis vende\n\nCasa 2 dormitórios\n\nTerreno 120m² 6x20\n\nCasa 67 m²\n\nCom área gourmet nos fundos , com churrasqueira, fogão, pia , mesa e banheiro.\n\nAs informações estão sujeitas a alterações. Consulte o corretor responsável.',
    price: 228000,
    location: 'Rua Maria Ana da Costa - Parque Granja Esperança - Cachoeirinha/RS - 94960-800',
    bedrooms: 2,
    bathrooms: 2, // 1 na casa + 1 na área gourmet
    area: 67,
    images: [
      '/casaparquegranjaesperança/capaprincipal.jpg',
      '/casaparquegranjaesperança/foto1.jpg',
      '/casaparquegranjaesperança/foto2.jpg',
      '/casaparquegranjaesperança/foto3.jpg',
      '/casaparquegranjaesperança/foto4.jpg',
      '/casaparquegranjaesperança/foto5.jpg',
      '/casaparquegranjaesperança/foto6.jpg',
    ],
    features: ['Área Gourmet com Churrasqueira', '2 Dormitórios', 'Vaga de Garagem'],
    featured: true,
  },
  {
    id: '2',
    title: 'Apartamento em Porto Gravataí',
    type: 'Apartamento',
    description: 'Ótima Localização e praticidade\n\nBuscando uma moradia com ótima localização, aqui está a oportunidade pra você.\n\nEste ótimo apto. com 2 dormitórios, mobiliado e condominio com toda a infraestrutura, um belíssimo salão de festas, piscinas adulto e infantil, playground, brinquedoteca e quiosques com churrasqueiras.\n\nLocalizado em uma região privilegiada, junto a av Dorival C. L. de Oliveira na pda 72, com uma rica infraestrutura comercial onde você vai ter farmácias, mercado, bazar, lotérica, ponto de ônibus há poucos metros de distância.\n\nPraticidade, comodidade e segurança são as palavras chaves que definem esse imóvel, sem falar no ótimo custo benefício.\n\nESPERAMOS VOCÊ PARA CONHECER ESSA OPORTUNIDADE!!!\n\nAs informações estão sujeitas a alterações. Consulte o corretor responsável.',
    price: 168000,
    location: 'Porto Gravataí - São Jerônimo - Gravataí/RS',
    bedrooms: 2,
    bathrooms: 1, // Assumindo 1 banheiro, pode ser ajustado
    area: 0, // Área não informada, pode ser ajustada
    images: [
      '/apartamento/capa.jpg',
      '/apartamento/img1.jpg',
      '/apartamento/img2.jpg',
      '/apartamento/img3.jpg',
      '/apartamento/img4.jpg',
      '/apartamento/img5.jpg',
      '/apartamento/img6.jpg'
    ],
    features: ['1 Vaga de Garagem', 'Mobiliado', 'Piscina no Condomínio', 'Salão de Festas', 'Playground', 'Quiosques com Churrasqueira'],
    featured: true,
  },
  {
    id: '3',
    title: 'Cobertura Duplex com Vista Panorâmica',
    type: 'Cobertura',
    description: 'Viva no topo do mundo nesta cobertura duplex exclusiva. Com uma piscina privativa, terraço amplo e vistas panorâmicas da cidade, esta propriedade é a definição de luxo urbano.',
    price: 2500000,
    location: 'Bairro Alto',
    bedrooms: 3,
    bathrooms: 4,
    area: 300,
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600', 'https://placehold.co/800x600'],
    features: ['Piscina Privativa', 'Terraço Gourmet', 'Vista Panorâmica', 'Elevador Privativo'],
    featured: true,
  },
  {
    id: '4',
    title: 'Terreno Amplo em Condomínio Fechado',
    type: 'Terreno',
    description: 'Excelente oportunidade para construir a casa dos seus sonhos. Terreno plano e espaçoso em condomínio fechado com segurança 24 horas e área de lazer completa.',
    price: 450000,
    location: 'Condomínio Vale Verde',
    bedrooms: 0,
    bathrooms: 0,
    area: 1000,
    images: ['https://placehold.co/800x600'],
    features: ['Segurança 24h', 'Clube', 'Área Verde', 'Pronto para Construir'],
    featured: false,
  },
  {
    id: '5',
    title: 'Apartamento Aconchegante Perto do Parque',
    type: 'Apartamento',
    description: 'Ideal para jovens casais ou solteiros, este apartamento está localizado a poucos passos do parque da cidade. Possui uma planta inteligente e uma varanda charmosa.',
    price: 550000,
    location: 'Vila Madalena',
    bedrooms: 1,
    bathrooms: 1,
    area: 60,
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600'],
    features: ['Perto do Parque', 'Cozinha Americana', 'Varanda', 'Condomínio com Lazer'],
    featured: true,
  },
  {
    id: '6',
    title: 'Casa de Vila Charmosa',
    type: 'Casa',
    description: 'Uma joia rara, esta casa de vila combina o charme do antigo com o conforto do moderno. Rua tranquila e arborizada, com fácil acesso a comércios e serviços.',
    price: 980000,
    location: 'Pinheiros',
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600'],
    features: ['Recém-reformada', 'Quintal com Churrasqueira', 'Rua Tranquila', 'Cozinha Integrada'],
    featured: true,
  },
  {
    id: '7',
    title: 'Apartamento com 3 Suítes',
    type: 'Apartamento',
    description: 'Apartamento espaçoso com três suítes, ideal para famílias que buscam conforto e privacidade. O condomínio oferece uma infraestrutura completa de lazer.',
    price: 1500000,
    location: 'Moema',
    bedrooms: 3,
    bathrooms: 4,
    area: 160,
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600'],
    features: ['3 Suítes', 'Varanda Gourmet', 'Piscina Aquecida', 'Salão de Festas'],
    featured: false,
  },
    {
    id: '8',
    title: 'Casa Térrea em Condomínio',
    type: 'Casa',
    description: 'Praticidade e conforto nesta casa térrea em condomínio. Com ambientes integrados e um quintal agradável, é perfeita para todas as idades.',
    price: 890000,
    location: 'Granja Viana',
    bedrooms: 3,
    bathrooms: 2,
    area: 170,
    images: ['https://placehold.co/800x600', 'https://placehold.co/800x600'],
    features: ['Casa Térrea', 'Ambientes Integrados', 'Quintal', 'Condomínio com Segurança'],
    featured: true,
  },
];
